// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlowqpzwdepdjqsebfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubG93cXB6d2RlcGRqcXNlYmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjY5NzMsImV4cCI6MjA2NzgwMjk3M30.UKb4_exNGuJGP4YAgksYjQcuRuxCiPWsZaqz4PD4Krs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});